### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by SepidehHashemzadeh** [Intel-bigdata/imllib-spark#12]
I tried to give an input with 600 fields and 13953 features and 2 factors. The size of input file is 41.1 MB. I encountered the " java.lang.OutOfMemoryError: Java heap space" . I tried to change the Spark configuration about executor memory from default value of 1G to 5G (which was the maximum amount allowed on my EMR cluster) by passing an argument when I submit the spark job still no luck. I have also attached an screenshot from my terminal.
<img width="260" alt="error" src="https://user-images.githubusercontent.com/17014954/29687110-22b6ae5e-88d0-11e7-9dfb-dd264a181cb6.png">

**Comment by VinceShieh** [comment]
First, please check this OOM issue happens on executor side or driver side. You just set the memory for the executor.
Also, try to increase the number of partition, though it might take a bit longer to compute.
next thing to try is setting spark.storage.memoryFraction (I dont think you would need to go that far)
given the input dataset, it seems 1G memory is enough, can you also try to run on a bare metal cluster instead of EMR, it seems EMR sometimes can get you weird issues when running spark job.

**Comment by VinceShieh** [comment]
pls contact us if the problem still exists. Close the issue now
